### ISSUE TITLE
Build STXXL RPM

### ISSUE THREAD

**Issue by jasonsurratt** [ngageoint/hootenanny-rpms#1]
@bmarchant @bwitham Do either of you guys want to take a whack at this?

You should be able to start with one of these src rpms:

https://www.rpmfind.net/linux/rpm2html/search.php?query=stxxl&submit=Search+...&system=&arch=src

Instructions for building are here:

https://wiki.centos.org/HowTos/RebuildSRPM

Basic steps will be:

1. Setup CentOS 6.7 VM
2. Get hoot compiling/running w/o stxxl
3. Build & Install RPM
4. Get hoot compiling/running with stxxl

I've got most of the RPMs for building/running in CentOS working now so ping me when you get to the second step.

**Comment by bmarchant** [comment]
@jasonsurratt I'll take this one on.  Sounds like an interesting one.

**Comment by jasonsurratt** [comment]
Thanks!
