### ISSUE TITLE
Update vagrant-test for recent Frechet changes

### ISSUE THREAD

**Issue by sputnam** [ngageoint/hootenanny-rpms#102]
After changes were recently made to hootenanny for frechet distance code, the `hoot-rpms-centos67` job started failing with the following output:
```
Failure: /home/vagrant/hootenanny-rpms/src/BUILD/hootenanny-0.2.31_94_g28b5a40/test-files/cmd/slow/ConflateCmdFrechetExactMatchInputsTest.sh
  src/main/cpp/hoot/test/ScriptTest.cpp(220)   - Expression: false
```
Talking with @bmarchant he noticed another test the frechet test relies on is excluded.  So for now we should need to exclude the frechet test until we turn on the other test.  The scope of this issue is to exclude the frechet test to get the build working again.

**Comment by bmarchant** [comment]
Issue fixed.
