### ISSUE TITLE
404 errors retrieving hootenanny-id/css/img files

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#109]
This bug occurs since the tomcat8 migration

**Comment by brianhatchl** [comment]
This bug also only occurs for tomcat8 on CentOS 6.7, not on Ubuntu 14.04.

But the fix was to add this line to /etc/tomcat8/context.xml just inside the `<Context allowLinking="true">` tag.

```
<Resources allowLinking="true" />
```
I don't know why the existing allowLinking attribute in Context doesn't fix this problem already.

**Comment by brianhatchl** [comment]
This change will have to be automated in the postinstall step of the hoot rpm spec file.

**Comment by brianhatchl** [comment]
Looks like the additional allowLinking was our RPMs change.  We just need to update the existing steps to add the Resource tag instead of modifying the Context tag.

https://github.com/ngageoint/hootenanny-rpms/blob/master/src/SPECS/hootenanny.spec.in#L355-L360

Still not sure why this is not a problem on Ubuntu vms.

**Comment by brianhatchl** [comment]
cc: @dmylov

**Comment by dmylov** [comment]
I've fixed this on the Ubuntu side as well.
The fix will be in a PR for https://github.com/ngageoint/hootenanny/issues/753

**Comment by sputnam** [comment]
@brianhatchl Do you think our fix last week took care of this?  Should I close it?  Or is there something still outstanding that needs to be done?

**Comment by brianhatchl** [comment]
From my local testing, I think we can close all three issues.

**Comment by sputnam** [comment]
This was merged, tested, and verified.  Setting to closed.
