### ISSUE TITLE
rpm saving and restoring tomcat config files will stomp customizations

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#111]
in the rpm install/uninstall we backup and then restore the tomcat config files.  however, if an admin makes further customization to this file those changes will get overwritten.

it might be best not to touch those files at all on uninstall.

**Comment by brianhatchl** [comment]
@sputnam @mattjdnv Do you think it important the the hoot services rpm tries to undo changes it makes to postgres and tomcat config files?  Or is leaving those modifications in place acceptable?

**Comment by mattjdnv** [comment]
I think, leave them in place.
