### ISSUE TITLE
Remove w3m

### ISSUE THREAD

**Issue by demmith** [ngageoint/hootenanny-rpms#126]
`w3m` has been removed from the hootenanny repo as it has been found to not be needed. The same needs to be done for the hootenanny-rpms repo.

**Comment by demmith** [comment]
The repo contains three occurrences of `w3m`. The are found in ...
`hootenanny-rpms/Makefile` (1x)
`hootenanny-rpms/src/SPECS/hootenanny.spec.in`  (2x)

**Comment by demmith** [comment]
Created new branch `126` and removed three occurrences of `w3m` from the two files noted earlier ...
`hootenanny-rpms/Makefile` (1x)
`hootenanny-rpms/src/SPECS/hootenanny.spec.in` (2x)
The changes have been committed and pushed to origin (126).
At this point I am holding off on the PR until such time as the `make vagrant-build` for this repo is in working order.

**Comment by bmarchant** [comment]
Come to find out this is a necessary part of `a2x` for creating text manuals.  Closing without changes.
