### ISSUE TITLE
Populate PreUpgrade and PostUpgrade handlers in services-ui rpm

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#22]
Figure out what needs to go in here when hootenanny-services-ui package is upgraded or reinstalled.

**Comment by brianhatchl** [comment]
Currently the post uninstall hook for the hootenanny-services-ui rpm will drop the hoot user and db from postgres.  See if rpm post uninstall can prompt for removal of hoot db and user.

**Comment by brianhatchl** [comment]
After some googling, it is not recommended that an rpm prompt for user input (as most a run unattended).
>Do not try to write interactive scripts. Many users install RPMs automatically. In such cases, or if the user runs a graphical RPM tool, any information your scripts output will be lost. User input will not be available.

Furthermore, postgresql package removal does not drop databases.  So using that behavior as a guide, removing the hootenanny-services-ui package will leave the hoot databases behind.

The rpm uninstall will also leave the 'upload' and 'ingest' folders created by hoot-services.  The 'upload' folder contains the shp, osm, and gdb files uploaded for ingest, but it seems to remove the files after they've been written to the db.  The ingest folder contains the uploaded imagery files that are tiled to create a custom imagery basemap, so the ingest folder should be preserved.

**Comment by jasonsurratt** [comment]
Sounds good to me.
