### ISSUE TITLE
Update hootenanny.spec to handle tomcat database resource

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#225]
Introduced here: https://github.com/ngageoint/hootenanny/pull/2584/files#diff-3250685b3f7f984af0feff69a8d9cdf2

To work with OAuth, the Hoot database resource had to be moved from dbcp2 to tomcat jndi connection pooling for deployment.

**Comment by sumarlidason** [comment]
hi @jbronn ,

we should be in merge territory soon, just wanted to touch base again on this:
looking at the current PR I think we want to keep the dynamic postgresql versioning, but revert the edits to tomcat's context.xml as the "internalized implementation" is working just fine.

@brianhatchl

**Comment by jbronn** [comment]
@sumarlidason I've updated the PR in #227 to be compatible with the latest changes and pushed a sample RPM as well.  This should be ready to go when the PR passes the full test suite.

**Comment by sumarlidason** [comment]
<3
