### ISSUE TITLE
Jenkins job error on services-ui branch

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#26]
```
ant
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
make[1]: Leaving directory `/home/vagrant/hootenanny-rpms/src/BUILD/gdal-1.10.1-fedora/swig/java'
make[1]: *** [build] Error 1
```
If pull request from master branch is run first and rpm build succeeds, the subsequent pull request from the services-ui branch will get past this error.  However is rpm build is run again from services-ui branch the error will occur.

**Comment by jasonsurratt** [comment]
This error does not occur on my clean build using vbox. I'll keep poking around.

**Comment by jasonsurratt** [comment]
Trying a second time on vbox I recreated the error.

```
rm -rf tmp/hootenanny
make clean-all
make vagrant-build && make vagrant-test
```

failed with:

```
libtool: link: (cd ".libs" && rm -f "libosrjni.so.1" && ln -s "libosrjni.so.1.17.1" "libosrjni.so.1")
libtool: link: (cd ".libs" && rm -f "libosrjni.so" && ln -s "libosrjni.so.1.17.1" "libosrjni.so")
libtool: link: ar cru .libs/libosrjni.a  osr_wrap.o
libtool: link: ranlib .libs/libosrjni.a
libtool: link: ( cd ".libs" && rm -f "libosrjni.la" && ln -s "../libosrjni.la" "libosrjni.la" )
cp ./.libs/*.so ./
ant
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
make[1]: *** [build] Error 1
make[1]: Leaving directory `/home/vagrant/hootenanny-rpms/src/BUILD/gdal-1.10.1-fedora/swig/java'
error: Bad exit status from /var/tmp/rpm-tmp.EWxldN (%build)


RPM build errors:
    Macro % has illegal name (%define)
    Bad exit status from /var/tmp/rpm-tmp.EWxldN (%build)
make: *** [RPMS/x86_64/gdal-1.10.1-3.el6.x86_64.rpm] Error 1
Connection to 127.0.0.1 closed.
make: *** [vagrant-build-archive] Error 2
```

**Comment by brianhatchl** [comment]
Trying to reproduce this myself on vbox with a clean clone of the repo.

**Comment by brianhatchl** [comment]
Yup, I got it too.

**Comment by jasonsurratt** [comment]
After getting the above error I re-ran make from the src directory and gdal built fine. Very odd. Though I'm still getting the issue here: https://github.com/ngageoint/hootenanny-rpms/pull/17#issuecomment-196525204

I've also recreated this in my Jenkins jrs-test-rpms-26 test dir on patty.

**Comment by jasonsurratt** [comment]
In `jrs-test-rpms-26` I found in the `java.opt` it was pointing `JAVA_HOME` to `/usr/lib/jvm/java-6-openjdk/` which doesn't exist. There was also a patch that hard coded the include to `JAVA_INCLUDE=-I/usr/lib/jvm/java/include/ -I/usr/lib/jvm/java/include/linux`. I changed `JAVA_HOME` to `JAVA_HOME=/usr/lib/jvm/java-1.6.0` and removed the hard coded include. I don't know if Java 6 is required, but it is more consistent with the original `java.opt`. I'm giving it a clean rebuild/test now.

Even if this fixes the problem, it still doesn't explain why the gdal build succeeds the second time. I'll keep poking...

**Comment by jasonsurratt** [comment]
Another bread crumb.

On services-ui:

`/etc/alternatives/java_sdk -> /usr/lib/jvm/java-1.7.0-openjdk.x86_64`

On master:

`/etc/alternatives/java_sdk -> /usr/lib/jvm/java-1.6.0-openjdk.x86_64`

**Comment by jasonsurratt** [comment]
Artificially recreating the situation in the GNUmakefile

```
[vagrant@localhost java]$ export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/
[vagrant@localhost java]$ ant
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
```

This possibly explains how we're getting the error the first time. I still don't know how it fixes itself.

**Comment by jasonsurratt** [comment]
After making the java.opts change the build is getting past the gdal compile in `jrs-test-rpms-26`. Will push the change to `services-ui`.

**Comment by jasonsurratt** [comment]
Resolved in the services-ui branch.
