### ISSUE TITLE
Add Tomcat configuration to rpm install script - r6921

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-rpms#3]
Similar to what's in: 

https://github.com/ngageoint/hootenanny/blob/develop/scripts/InstallHoot-CentOS-RHEL.sh

**Comment by brianhatchl** [comment]
See https://github.com/ngageoint/hootenanny-rpms/commit/fa3cdbe7976d434e4378cb99dce095e613d7c168?w=1 and https://github.com/ngageoint/hootenanny/commit/3e380cc552a56f378046eae68f9ccb492e047aea
