### ISSUE TITLE
Ensure node-mapnik-server npm dependencies are installed

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#32]
Not sure how hoot core RPM handles node modules.  Node-mapnik-server uses npm to install them, but not sure if those modules need to be bundled with the rpm the way we do non-base/epel packages or if they are available on the network.

**Comment by jasonsurratt** [comment]
I hadn't considered that. Does npm have a non-network mode?

**Comment by brianhatchl** [comment]
Not sure, what about the node modules required by HootJS?
>xml2js htmlparser imagemagick mocha@1.20.1 express@3.1.2 async html-to-text restler

**Comment by brianhatchl** [comment]
We don't commit the node_modules folder to the git repo, but during rpm build we could run `npm install` and then the node_modules folder would be included with the node-mapnik-server/ files copied by the rpm.

**Comment by jasonsurratt** [comment]
That sounds good.

**Comment by brianhatchl** [comment]
Will confirm this is working when we make a CentOS 7 RPM.
