### ISSUE TITLE
Node-mapnik won't run on CentOs 6.7 ( dependency issue )

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#33]
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/lib/ho
otenanny/node-mapnik-server/node_modules/mapnik/lib/binding/node-v11-linux-x64/m
apnik.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/lib/hootenanny/node-mapnik-server/node_modules/m
apnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by brianhatchl** [comment]
I've read this dependency should be present on CentOS 7

**Comment by jasonsurratt** [comment]
@qwyjibojones Have you run into this issue before? Any thoughts?

**Comment by jasonsurratt** [comment]
Possibly build from source?

https://github.com/mapnik/node-mapnik#source-build

**Comment by brianhatchl** [comment]
Yes, @qwyjibojones reported it after the first release of Hoot containing node-mapnik was installed on CentOS 6.5.  I believe he's pursuing the build from source option, but to this date is still unresolved.

**Comment by jasonsurratt** [comment]
@qwyjibojones, Have you made any progress on this? If not, mind if I give it a go?

**Comment by jasonsurratt** [comment]
Looks like Mapnik is going to be a bear to install. I started with the "easy" path of building the source RPM for Mapnik and got the following requirements:

* mapnik
 * (bunch of easy stuff)
 * harffbuzz
   * graphite2
     * texlive (version we don't have, run away!)
      * python2-fonttools

This may be a silly question, but how critical is a Mapnik on CentOS 6.7?

On that same vein, what version of Mapnik do you need? The latest version requires a g++ upgrade on CentOS just to compile.

**Comment by brianhatchl** [comment]
I think it's reasonable to have node-mapnik-server as "unsupported" until we upgrade to CentOS 7

**Comment by jasonsurratt** [comment]
Uh, yeah. That sounds good.
