### ISSUE TITLE
ServicesDb test error on jenkins

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#37]
http://selma:8765/job/hoot-rpms-pull-request-centos67/98/console

>==> default: .19:39:51.503 WARN  ...?(  -1) Unable to free statement: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>==> default: 19:39:51.503 WARN  ...?(  -1) Unable to free statement: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>==> default: 
>==> default: 19:39:51.503 WARN  ...pp/hoot/core/io/ServicesDb.cpp( 126) Closing database before transaction is committed. Rolling back transaction.
>==> default: E
>==> default: Failure: N4hoot14ServicesDbTestE::runDropMapTest
>==> default:   (-1)   - Error finding user with the email: ServicesDbTest@hoottestcpp.org ERROR:  current transaction is aborted, commands ignored until end of transaction block
>==> default: (25P02) QPSQL: Unable to create query

**Comment by jasonsurratt** [comment]
Sadly this appears to be an issue that is fixed the second time you run the test. I was also able to successfully run the other "Service*" tests after the script test succeeded.

**Comment by jasonsurratt** [comment]
This should be fixed by: https://github.com/ngageoint/hootenanny/pull/479/commits/820befb53539e962df4128df6cfacc9b8d65dfe4

**Comment by jasonsurratt** [comment]
After the above is merged we should be able to remove the "Service" related exclude flags.
