### ISSUE TITLE
test-files/cmd/slow/ConflationStatsReportTest.sh fails on rpm build vm

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#41]
This is the line, 
># Make sure the expected files are listed.
echo Output files:
ls test-output/cmd/csr/ | sort

and we piped the output to sort to try to fix, but the error persists.  Seems to me like the expected output (in the left column) is incorrect, but this test should be failing on all other jenkins jobs I would think.

![screenshot from 2016-03-23 14 50 52](https://cloud.githubusercontent.com/assets/2600932/13997093/cac0559a-f106-11e5-9c79-37c3a4c12c11.png)

**Comment by jasonsurratt** [comment]
On my vsphere VM I'm getting this:

```
[vagrant@hoot-nightly-build hootenanny]$ ls test-output/cmd/csr/ | sort
areaHistogram.png
conflatedFeature.png
csr2.osm
csr.asciidoc
csr.html
csr.osm
csr.pdf
csrStats.txt
distancesHistogram.png
...
```

`2` comes after `.` in the ascii table. Looks like the locale impacts things. E.g.

```
[vagrant@hoot-nightly-build hootenanny]$ ls test-output/cmd/csr/ | LC_ALL=C sort 
areaHistogram.png
conflatedFeature.png
csr.asciidoc
csr.html
csr.osm
csr.pdf
csr2.osm
csrStats.txt
...
```

I'll make the appropriate change in core.

**Comment by jasonsurratt** [comment]
See: https://github.com/ngageoint/hootenanny/pull/496

**Comment by jasonsurratt** [comment]
Change succeeded in nightly build.

**Comment by brianhatchl** [comment]
was waiting for #25 to clear up before creating pull request to enable this test in rpm.

**Comment by jasonsurratt** [comment]
The fix was in the core. A pull request isn't necessary here.

**Comment by brianhatchl** [comment]
We still need to enable the test then,
https://github.com/ngageoint/hootenanny-rpms/blob/master/src/SPECS/hootenanny.spec.in#L113

**Comment by jasonsurratt** [comment]
I'm testing #25 in another VM now which will take a while. This is a fairly isolated change so I've added the pull request and hopefully we can close it out shortly.
