### ISSUE TITLE
Speed up RPM building

### ISSUE THREAD

**Issue by jasonsurratt** [ngageoint/hootenanny-rpms#43]
Investigate ways to build RPMs in parallel

**Comment by brianhatchl** [comment]
Job still ran in 2hrs 19min, was that with 'vagrant clean' or with the shortcuts still in place?

**Comment by jasonsurratt** [comment]
That includes a clean all. Without these changes that takes 2 hrs 44min (http://selma:8765/job/hoot-rpms-pull-request-centos67/117/). 25min improvement is still something. If you don't run a clean-all then this won't make much change.
