### ISSUE TITLE
Create a hootenanny-test package

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-rpms#46]
Would it be a good idea to create a test package that will allow running the hoot-ui cucumber tests on a RPM deployed hoot system?  The core tests could also be packaged here as well if this made sense.

**Comment by jasonsurratt** [comment]
Yeah, I think this is a good idea.

**Comment by brianhatchl** [comment]
This task is impeded by the fact that recent versions of Chrome and Chromedriver and Cucumber dependencies aren't supported on CentOS 6.7 without major shenanigans.

**Comment by jasonsurratt** [comment]
Sounds like we should skip installing straight onto CentOS 6.7. We could do two vagrant instances for release testing. One for running cucumber, etc. in Ubuntu and the other for running services on CentOS. Dunno if that much work is justified at this point.

**Comment by brianhatchl** [comment]
With a recent change to the spec file that replaced passwords in db.properties, but had a typo that made the replacement fail, the need for integration tests (cucumber) to run on the hoot rpm deployed vm has come up again.

Another cucumber testing vm could be defined in the Vagrantfile.  Not sure how to coordinate the install of the rpm on the centos vm and then wait to run the tests on the other vm.  But probably worth looking into again.
