### ISSUE TITLE
iptables modification isn't working as expected

### ISSUE THREAD

**Issue by jasonsurratt** [ngageoint/hootenanny-rpms#50]
iptables fails:

From @qwyjibojones 

I tried the new RPM install on an AWS instance that started with a CentOS 6.5 from the marketplace. 
I added the epel repo and ran yum update which updated me to CentOS 6.7
I then added the hoot repo and ran the hootenanny-autostart install.

iptables is modified as follows:
----------------------------------------------------------------

*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
-A OUTPUT -d 127.0.0.0/8 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
COMMIT
# Completed on Wed Apr  6 14:41:53 2016
# Generated by iptables-save v1.4.7 on Wed Apr  6 14:41:53 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8000 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Wed Apr  6 14:41:53 2016
----------------------------------------------------------------

Line 18 is preventing the use of the remaining lines. iptables stops evaluating the rules when it sees that line. I removed that line and restarted iptables.

I addressed those in an new AWS instance built the same way and it works now. I can get to the service from the office at http://XXX.XXX.XXX.XXX:8080/hootenanny-id/
The 80 forward does not work for some reason still working on that...

**Comment by jasonsurratt** [comment]
@brianhatchl

**Comment by brianhatchl** [comment]
I hope to have addressed this issue in commits https://github.com/ngageoint/hootenanny-rpms/pull/48/commits/f7b83bccc140c0f87083c0a589d87a545e672cc7 and https://github.com/ngageoint/hootenanny-rpms/pull/48/commits/d52e0e221efac3cc618c52fec0163a0273b23fc3 by inserting rather than appending the rules for hoot.

I'm thinking now we need to add ports 8094 and 8096 for the node translation and p2pmerge services.

**Comment by brianhatchl** [comment]
@qwyjibojones Ready for test on a fresh CentOS instance.  We want to make sure it works without any fiddling.

**Comment by jasonsurratt** [comment]
I think you need to make sure you install this version:

`hootenanny-autostart-0.2.23_595_g071eaf3-1.el6.x86_64.rpm`

The _596_ version doesn't include Brian's changes. If all goes well the "latest" will have the right changes in an hour or so.

**Comment by brianhatchl** [comment]
@qwyjibojones were you able to test these fixes installing hoot rpms on the aws centos instance?

**Comment by qwyjibojones** [comment]
This is working as expected now. 
Here is the end result for the iptables file:

# Generated by iptables-save v1.4.7 on Fri Apr 15 18:50:25 2016
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080 
-A OUTPUT -d 127.0.0.0/8 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080 
COMMIT
# Completed on Fri Apr 15 18:50:25 2016
# Generated by iptables-save v1.4.7 on Fri Apr 15 18:50:25 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8000 -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
-A INPUT -p icmp -j ACCEPT 
-A INPUT -i lo -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -j REJECT --reject-with icmp-host-prohibited 
-A FORWARD -j REJECT --reject-with icmp-host-prohibited 
COMMIT
# Completed on Fri Apr 15 18:50:25 2016

**Comment by qwyjibojones** [comment]
Closing.
